stages:
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/bundle

.ruby:
  image: ruby:3.4-slim
  before_script:
    - apt-get --quiet --quiet update
    - apt-get --quiet --yes -o=Dpkg::Use-Pty=0 install build-essential libpq-dev libxml2-dev libyaml-dev git
    - gem install bundler -v '~> 2.0'
    - bundle config --local frozen 'true'
    - bundle config --local path '.cache/bundle'
    - bundle config --local without 'development production integration'
    - bundle install --jobs $(nproc) --retry 3
  after_script:
    - bundle clean

lint:rubocop:
  extends: .ruby
  script:
    - bundle exec rubocop --parallel

build:image:
  stage: build
  image: docker:27
  services:
    - name: docker:27-dind
      command: ["--registry-mirror", "https://mirror.registry.openhpi.cloud"]
  variables:
    REGISTRY: $CI_REGISTRY_IMAGE/
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd docker/
    - >
      docker buildx bake
      --allow=fs.read=..
      -f docker-bake.hcl
      --set "*.cache-from=type=registry,ref=$CI_REGISTRY_IMAGE/xikolo-lanalytics:latest"
      --push
      lanalytics
