stages:
  - lint
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/bundle

rubocop:
  stage: lint
  image: ruby:2.7-slim
  before_script:
    - apt-get -qq update
    - apt-get -qqy -o=Dpkg::Use-Pty=0 install build-essential cmake libpq-dev libxml2-dev pkg-config
    - gem install bundler -v '~> 2.0'
    - bundle install -j $(nproc) --retry 3 --path .cache/bundle --without development production integration
  script: bundle exec pronto run --commit origin/master --exit-code
  except:
    refs: [master]

fossa:analyze:
  stage: test
  image: registry.xikolo.de/docker/fossa:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}---fossa
    paths:
      - vendor/ruby
  only:
    refs:
      - merge_requests
    changes:
      - Gemfile.lock
  before_script:
    - bundle install --frozen --jobs 32 --retry 3 --clean --path vendor
  script:
    - fossa analyze
    - fossa test --timeout 1200
