inherit_gem:
  xikolo-lint: default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2

Metrics/BlockLength:
  Exclude:
    - 'lib/lanalytics/metric/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/lanalytics/metric/*.rb'

Rails/ActiveSupportAliases:
  Enabled: false
