AllCops:
  Exclude:
    - 'vendor/**'
    - 'db/schema.rb'
    - 'bin/**'
    - 'config/initializers/integration*'
  TargetRubyVersion: 2.3


Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrations/**.rb'
    - 'spec/**/*_spec.rb'

Rails/FilePath:
  Enabled: false

Rails/ApplicationRecord:
  Exclude:
    - 'db/**/*'


Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space


Lint/AmbiguousBlockAssociation:
  Enabled: false


Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile


Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RescueModifier:
  Exclude:
    - '**/*_spec.rb'

Style/RescueStandardError:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/Semicolon:
  Exclude:
    - '**/*_spec.rb'

Style/SignalException:
  EnforcedStyle: only_raise


Metrics/BlockLength:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - '**/*.rake'

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
