xikolo.account.user.url: 'http://account.xikolo.tld/users.json'
xikolo.account.user.create: &XIKOLO_ACCOUNT_USER_PROCESSING_CHAIN
  - Lanalytics::Processing::Filter::UserDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
xikolo.account.user.update:
  *XIKOLO_ACCOUNT_USER_PROCESSING_CHAIN
xikolo.account.user.destroy: 
  *XIKOLO_ACCOUNT_USER_PROCESSING_CHAIN


xikolo.course.course.url: 'http://course.xikolo.tld/courses.json'
xikolo.course.course.create: &XIKOLO_COURSE_COURSE_PROCESSING_CHAIN
  - Lanalytics::Processing::Filter::CourseDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
xikolo.course.course.update:
  *XIKOLO_COURSE_COURSE_PROCESSING_CHAIN
