production:
  qc_rules_sync:
    cron: '*/15 * * * *'
    class: CheckAllRulesWorker
    queue: high
  calculate_course_statistics:
    cron: '0 0 * * *'
    class: CalculateCourseStatsWorker
    queue: high
  calculate_section_conversions:
    cron: '0 2 * * *'
    class: CalculateSectionConversionsWorker
    queue: high
