common: &common
  datasources:
    - exp_events_elastic.yml     # uses exp_events pipeline
    - exp_events_postgres.yml    # uses exp_events pipeline
    - link_tracking_events_elastic.yml
  pipelines:
    - exp_events_pipeline.prb
    - link_tracking_events_pipeline.prb

development:
  <<: *common

test:
  <<: *common

integration:
  <<: *common

staging:
  <<: *common

production:
  <<: *common