common: &common
  datasources:
    - referral.yml
    - exp_api_elastic.yml   # uses exp_api pipeline
    - exp_api_native.yml    # uses exp_api pipeline
  pipelines:
    - exp_api_pipeline.prb
    - referrer_pipeline.prb

development:
  datasources:
    - referral.yml
    - exp_api_elastic.yml   # uses exp_api pipeline
    - exp_api_native.yml    # uses exp_api pipeline
  pipelines:
    - exp_api_pipeline.prb
    - referrer_pipeline.prb

test:
  <<: *common

integration:
  <<: *common

staging:
  <<: *common

production:
  <<: *common