common: &common
  datasources:
    - moocdb_postgresql.yml
    - exp_api_elastic.yml
    # - experience_graph_schema_neo4j_datasource.yml
  pipelines:
    - moocdb_pipeline.prb
    - exp_api_pipeline.prb
    # - experience_graph_pipeline.prb
    # - referrer_pipeline.prb

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  datasources:
    - exp_api_elastic.yml
    - moocdb_postgresql.yml
    # - experience_graph_schema_neo4j_datasource.yml
  pipelines:
    - exp_api_pipeline.prb
    - moocdb_pipeline.prb
    # - experience_graph_pipeline.prb
    # - referrer_pipeline.prb
