common: &common
  datasources:
    # - experience_graph_schema_neo4j_datasource.yml
    - moocdb_postgresql.yml
    - exp_api_elastic.yml
  pipelines:
    - experience_graph_pipeline.prb
    - moocdb_pipeline.prb
    - exp_api_pipeline.prb
    - referrer_pipeline.prb

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
