common: &common
  datasources:
    - experience_graph_schema_neo4j.yml
    - moocdb_postgresql.yml
    - exp_api_elastic.yml
  pipelines:
    - exp_api_pipeline.rb
    - experience_graph_pipeline.rb
    - moocdb_pipeline.rb

development:
  <<: *common

test:
  datasources:
    # - experience_graph_schema_neo4j_datasource.yml
    - moocdb_postgresql.yml
    - exp_api_elastic.yml
  pipelines:
    # - experience_graph_pipeline.rb
    - moocdb_pipeline.rb
    - exp_api_pipeline.rb
  # No datasources or pipelines defined so that the tests pass
  # pipelines:
  #   - exp_api_pipeline.rb
  #   # - experience_graph_pipeline.rb
  #   - moocdb_pipeline.rb

staging:
  <<: *common

production:
  <<: *common
