# ------------------- User Domain Entities -------------------
xikolo.account.user.create: '/users.json'


# ------------------- Course Domain Entities -------------------
xikolo.course.course.create: '/courses.json'
xikolo.course.item.create: '/items.json'
xikolo.course.enrollment.create: '/enrollments.json'


# ------------------- Learning Room Domain Entities -------------------
xikolo.collabspace.collab_space.create: '/collab_spaces.json'
xikolo.collabspace.membership.create: '/memberships.json'


# ------------------- Submission Domain Entities -------------------
# TODO include this url


# ------------------- Pinboard Domain Entities -------------------
xikolo.pinboard.question.create: '/questions.json'
xikolo.pinboard.subscription.create: '/subscriptions.json'
xikolo.pinboard.answer.create: '/answers.json'
xikolo.pinboard.comment.create: '/comments.json'