# Instead of constantly modifying this file and not checking it in,
# let's have every branch commit its own development settings
# and keep production seperate from that.

common: &common
  datasources:
    #- moocdb_postgresql.yml
    - exp_api_elastic.yml   # uses exp_api pipeline
    # - exp_api_native.yml    # uses exp_api pipeline
    # - experience_graph_schema_neo4j_datasource.yml
  pipelines:
   # - moocdb_pipeline.prb
    - exp_api_pipeline.prb
    # - experience_graph_pipeline.prb
    # - referrer_pipeline.prb

development:
  datasources:
    #- moocdb_postgresql.yml
    - exp_api_elastic.yml   # uses exp_api pipeline
    #- exp_api_native.yml    # uses exp_api pipeline
    # - experience_graph_schema_neo4j_datasource.yml
  pipelines:
    #- moocdb_pipeline.prb
    - exp_api_pipeline.prb
    # - experience_graph_pipeline.prb
    - referrer_pipeline.prb

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
