common: &common
  datasources:
    # - experience_graph_schema_neo4j_datasource.yml
    - moocdb_postgresql.yml
    - exp_api_elastic.yml
  pipelines:
    # - experience_graph_pipeline.rb
    - moocdb_pipeline.rb
    - exp_api_pipeline.rb

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
