# Mnemosyne AMQP sink

common: &common
  # AMQP server endpoint
  server: <%= ENV['XIKOLO_RABBITMQ_URL'] || 'amqp://localhost' %>

  # # Platform identifier to group applications
  # platform: default
  #
  # # AMQP exchange name, must be a topic exchange
  # exchange: mnemosyne
  #
  # # Application name, defaults to rails application name
  # application:
  #
  # # Hostname reported with traces, default to machine hostname
  # hostname:

development:
  <<: *common

test:
  enabled: false

production:
  <<: *common
