# Neo4j
# Make sure that gem 'neo4j-core' is in your Gemfile

development:
  db_type: server_db
  db_url: 'http://localhost:7474'

test:
  # db_type: embedded_db
  # db_url: 'db/test/neo4j'
  db_type: server_db
  db_url: 'http://localhost:8474'

# production:
  # <<: *default
#  database: db/production.sqlite3
