roles:
  # Admins are allowed to mark alerts as ignored for all users
  lanalytics.report.admin:
    - lanalytics.report.create
    - lanalytics.report.delete
  lanalytics.report.inspector:
    - lanalytics.report.create.anonymous
    - lanalytics.report.delete
