roles:
  # Admins are allowed to mark alerts as ignored for all users
  lanalytics.alert.admin:
    - lanalytics.alert.ignore
  lanalytics.alert.inspector:
    - lanalytics.alert.index
  lanalytics.report.admin:
    - lanalytics.report.create
  lanalytics.report.inspector:
    - lanalytics.report.create.anonymous
  lanalytics.rule.admin:
    - lanalytics.rule.manage

grants:
  - role: lanalytics.alert.admin
    group: xikolo.admins
    context: root
  - role: lanalytics.alert.inspector
    group: xikolo.admins
    context: root
  - role: lanalytics.report.inspector
    group: xikolo.admins
    context: root
  - role: lanalytics.rule.admin
    group: xikolo.admins
    context: root
