# Postgres Database Configuration
# Make sure that gem 'pg' is in your Gemfile

development:
  dbname: lanalytics-development

test:
  dbname: lanalytics-test

production:
  dbname: lanalytics-production
