# ------------------- User Domain Entities -------------------
xikolo.account.user.url: 'http://localhost:3100/users.json'
xikolo.account.user.create: &XIKOLO_ACCOUNT_USER_PROCESSING_CHAIN
  - Lanalytics::Processing::Filter::UserDataFilter.new
  - Lanalytics::Processing::Filter::AnonymousDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new
xikolo.account.user.update:
  *XIKOLO_ACCOUNT_USER_PROCESSING_CHAIN
xikolo.account.user.destroy: 
  *XIKOLO_ACCOUNT_USER_PROCESSING_CHAIN
  


# ------------------- Course Domain Entities -------------------
xikolo.course.course.url: 'http://localhost:3300/courses.json'
xikolo.course.course.create: &XIKOLO_COURSE_COURSE_PROCESSING_CHAIN
  - Lanalytics::Processing::Filter::CourseDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new
xikolo.course.course.update:
  *XIKOLO_COURSE_COURSE_PROCESSING_CHAIN
xikolo.course.course.destroy:
  *XIKOLO_COURSE_COURSE_PROCESSING_CHAIN

xikolo.course.item.url: 'http://localhost:3300/items.json'
xikolo.course.item.create:
  - Lanalytics::Processing::Filter::ItemDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new

xikolo.course.enrollment.url: 'http://localhost:3300/enrollments.json'
xikolo.course.enrollment.create:
  - Lanalytics::Processing::Filter::MembershipDataFilter.new(:user_id, :course_id, :ENROLLED)
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new
xikolo.course.enrollment.destroy:
  - Lanalytics::Processing::Filter::MembershipDataFilter.new(:user_id, :course_id, :UN_ENROLLED)
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new

xikolo.course.visit.create:
  - Lanalytics::Processing::Filter::MembershipDataFilter.new(:user_id, :item_id, :PROGRESSED)
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new



# ------------------- Learning Room Domain Entities -------------------
xikolo.learning_room.learning_room.url: 'http://localhost:4800/learning_rooms.json'
xikolo.learning_room.learning_room.create: &LEARNING_ROOM_PROCESSING_CHAIN
  - Lanalytics::Processing::Filter::LearningRoomDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new
xikolo.learning_room.learning_room.update:
  *LEARNING_ROOM_PROCESSING_CHAIN
xikolo.learning_room.learning_room.destroy:
  *LEARNING_ROOM_PROCESSING_CHAIN

xikolo.learning_room.membership.url: 'http://localhost:4800/memberships.json'
xikolo.learning_room.membership.create:
  - Lanalytics::Processing::Filter::MembershipDataFilter.new(:user_id, :learning_room_id, :JOINED)
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new
xikolo.learning_room.membership.destroy:
  - Lanalytics::Processing::Filter::MembershipDataFilter.new(:user_id, :learning_room_id, :UN_JOINED)
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new



# ------------------- Submission Domain Entities -------------------
xikolo.submission.submission.create:
  - Lanalytics::Processing::Filter::MembershipDataFilter.new(:user_id, :item_id, :SUBMITTED)
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new



# ------------------- Pinboard Domain Entities -------------------
xikolo.pinboard.question.url: http://localhost:3500/questions.json
xikolo.pinboard.question.create: &PINBOARD_QUESTION_PROCESSING_CHAIN
  - Lanalytics::Processing::Filter::PinboardQuestionDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new
xikolo.pinboard.question.update:
  *PINBOARD_QUESTION_PROCESSING_CHAIN

xikolo.pinboard.subscription.url: 'http://localhost:3500/subscriptions.json'
xikolo.pinboard.subscription.create:
  - Lanalytics::Processing::Filter::MembershipDataFilter.new(:user_id, :question_id, :SUBSCRIBED)
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new
xikolo.pinboard.subscription.destroy:
  - Lanalytics::Processing::Filter::MembershipDataFilter.new(:user_id, :question_id, :UN_SUBSCRIBED)
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new

xikolo.pinboard.answer.url: 'http://localhost:3500/answers.json'
xikolo.pinboard.answer.create: &PINBOARD_ANSWER_PROCESSING_CHAIN
  - Lanalytics::Processing::Filter::PinboardAnswerDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new
xikolo.pinboard.answer.update:
  *PINBOARD_ANSWER_PROCESSING_CHAIN


xikolo.pinboard.comment.url: http://localhost:3500/comments.json
xikolo.pinboard.comment.create:
  - Lanalytics::Processing::Filter::PinboardCommentDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new



# ------------------- Helpdesk Domain Entities -------------------
xikolo.helpdesk.ticket.create:
  - Lanalytics::Processing::Filter::HelpdeskTicketDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new



# ------------------- Web Events -------------------
xikolo.web.event.create:
  - Lanalytics::Processing::Filter::ExpApiStatementDataFilter.new
  - Lanalytics::Processing::Processor::LoggerProcessor.new
  - Lanalytics::Processing::Processor::Neo4jProcessor.new