common: &common
  uri: amqp://localhost/
  # autostart: true - we do not need this because we start the Msgr.client explicitly in initializers/02_lanalytics_start_msgr.rb

development:
  <<: *common

test:
  <<: *common

integration:
  <<: *common

staging:
  <<: *common

production:
  <<: *common