common: &common
  uri: <%= ENV['XIKOLO_RABBITMQ_URL'] || 'amqp://localhost/' %>

development:
  <<: *common

test:
  <<: *common
  prefix: lanalytics-test
  pool_class: Msgr::TestPool
  raise_exceptions: true

integration:
  <<: *common

staging:
  <<: *common

production:
  <<: *common