common: &common
  uri: amqp://localhost/

test:
  <<: *common

development:
  <<: *common
  autostart: true

production:
  uri: amqp://openhpi:YwoXVln8AyTCang1USfA@10.210.0.31/openhpi
  autostart: false
