common: &common
  uri: <%= ENV['XIKOLO_RABBITMQ_URL'] || 'amqp://localhost/' %>
  # autostart: true - we do not need this because we start the Msgr.client explicitly in initializers/02_lanalytics_start_msgr.rb

development:
  <<: *common

test:
  <<: *common
  prefix: lanalytics-test
  pool_class: Msgr::TestPool
  raise_exceptions: true

integration:
  <<: *common

staging:
  <<: *common

production:
  <<: *common