development: &dev
  services: &devserv
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    notification: <%= ENV['XIKOLO_SERVICE_NOTIFICATION'] || 'http://localhost:3200' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    pinboard: <%= ENV['XIKOLO_SERVICE_PINBOARD'] || 'http://localhost:3500' %>
    video: <%= ENV['XIKOLO_SERVICE_VIDEO'] || 'http://localhost:3600' %>
    quiz: <%= ENV['XIKOLO_SERVICE_QUIZ'] || 'http://localhost:3800' %>
    news: <%= ENV['XIKOLO_SERVICE_NEWS'] || 'http://localhost:4300' %>
    collabspace: <%= ENV['XIKOLO_SERVICE_LEARNING_ROOM'] || 'http://localhost:4800' %>
    progress: <%= ENV['XIKOLO_SERVICE_PROGRESS'] || 'http://localhost:4900' %>
    peerassessment: <%= ENV['XIKOLO_SERVICE_PEERASSESSMENT'] || 'http://localhost:5400' %>

test:
  services:
    account: http://account.xikolo.tld
    collabspace: http://collabspace.xikolo.tld
    course: http://course.xikolo.tld
    news: http://news.xikolo.tld
    notification: http://notification.xikolo.tld
    pinboard: http://pinboard.xikolo.tld
    quiz: http://quiz.xikolo.tld
    video: http://video.xikolo.tld

staging:
  services:
    <<: *devserv

production:
  services:
    account: http://services:8080/account
    notification: http://services:8080/notification
    course: http://services:8080/course
    pinboard: http://services:8080/pinboard
    video: http://services:8080/video
    quiz: http://services:8080/quiz
    news: http://services:8080/news
    progress: http://services:8080/progress
    peer_assessment: http://services:8080/peerassessment
