common: &common
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    collabspace: <%= ENV['XIKOLO_SERVICE_LEARNING_ROOM'] || 'http://localhost:4800' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    news: <%= ENV['XIKOLO_SERVICE_NEWS'] || 'http://localhost:4300' %>
    notification: <%= ENV['XIKOLO_SERVICE_NOTIFICATION'] || 'http://localhost:3200' %>
    peerassessment: <%= ENV['XIKOLO_SERVICE_PEERASSESSMENT'] || 'http://localhost:5400' %>
    pinboard: <%= ENV['XIKOLO_SERVICE_PINBOARD'] || 'http://localhost:3500' %>
    quiz: <%= ENV['XIKOLO_SERVICE_QUIZ'] || 'http://localhost:3800' %>

development:
  <<: *common

production:
  <<: *common

test:
  services:
    account: http://account.xikolo.tld
    collabspace: http://collabspace.xikolo.tld
    course: http://course.xikolo.tld
    news: http://news.xikolo.tld
    notification: http://notification.xikolo.tld
    pinboard: http://pinboard.xikolo.tld
    quiz: http://quiz.xikolo.tld
