---
# Limited by database pool size
:concurrency: 5
:verbose: true

# This configuration is ignored in production. The queues are explicitly
# passed to the Debian services in their configs.
:queues:
  - high
  - default
  - reports_default
  - reports_long_running
