#

common: &common
  url: <%= ENV.fetch("SIDEKIQ_REDIS_URL", nil) %>
  pool_timeout: 5
  network_timeout: 5

development:
  <<: *common
  db: 5901

test:
  <<: *common
  db: 5902

integration:
  <<: *common
  db: 5903

production:
  <<: *common
  db: 5901
