# Postgres Database Configuration
# Make sure that gem 'pg' is in your Gemfile

common: &common
  datasource_adapter: 'PostgresqlDatasource'
  adapter: postgresql
  key: 'exp_api_native'
  name: 'Exp API on PostgreSQL'
  description: 'Simply storing exp api events in a relational database.'
  pool: 5

development:
  <<: *common
  database: xikolo-learnanalytics-development

test:
  <<: *common
  database: xikolo-learnanalytics-test

integration:
  <<: *common
  database: xikolo-learnanalytics-integration

staging:
  <<: *common
  database: db/staging.sqlite3

production:
  <<: *common
  database: db/production.sqlite3
