# Postgres Database Configuration
# Make sure that gem 'pg' is in your Gemfile

common: &common
  datasource_adapter: 'PostgresqlDatasource'
  adapter: postgresql
  key: 'exp_events_postgres'
  name: 'Experience Events on Postgres'
  description: 'User Interaction Events'
  pool: 5

development:
  <<: *common
  database: xikolo-learnanalytics-development

test:
  <<: *common
  database: xikolo-learnanalytics-test

integration:
  <<: *common
  database: xikolo-learnanalytics-integration

staging:
  <<: *common
  database: db/staging.sqlite3

production:
  <<: *common
  database: db/production.sqlite3
