#  ElasticDatasource Database Configuration

common: &common
  datasource_adapter: 'ElasticDatasource'
  key: 'exp_api_elastic'
  name: 'Experience API On ElasticSearch '
  description: 'Learning Record Store containing all activity from MOOC students in the Experience API Schema. Try out some of the queries ...'

development:
  <<: *common
  host: 'localhost'
  port: '9200'
  index: 'lanalytics'
  user: 'lanalytics'
  password: 'lanalytics'

test:
  <<: *common

integration:
  <<: *common

staging:
  <<: *common
  host: 'localhost'
  port: '10200'
  index: 'lanalytics'
  user: 'lanalytics'
  password: 'lanalytics'

production:
  <<: *common
