#  ElasticDatasource Database Configuration

common: &common
  datasource_adapter: 'ElasticDatasource'
  key: 'link_tracking_events_elastic'
  name: 'Link Tracking on Elastic'
  description: 'Tracking internal and external links'

development:
  <<: *common
  host: 'localhost'
  port: '9200'
  index: 'link_tracking'
  user: 'lanalytics'
  password: 'lanalytics'

test:
  <<: *common

integration:
  <<: *common
  host: 'localhost'
  port: '9200'
  index: 'lanalytics'
  user: 'lanalytics'
  password: 'lanalytics'

staging:
  <<: *common
  host: 'localhost'
  port: '10200'
  index: 'lanalytics'
  user: 'lanalytics'
  password: 'lanalytics'

production:
  <<: *common
