# Postgres Database Configuration
# Make sure that gem 'pg' is in your Gemfile

common: &common
  datasource_adapter: 'PostgresqlDatasource'
  adapter: postgresql
  key: 'moocdb_postgresql'
  name: 'MOOCdb on PostgreSQL'
  description: 'The MOOCdb project aims to brings together education researchers, computer science researchers, machine learning researchers, technologists, database and big data experts to advance MOOC data science. The openHPI Team wants to contribute to this project by providing their data in the proposed schema.'
  pool: 5

development:
  <<: *common
  database: xikolo-learnanalytics-development

test:
  <<: *common
  database: xikolo-learnanalytics-test

integration:
  <<: *common
  database: xikolo-learnanalytics-integration

staging:
  <<: *common
  database: xikolo-learnanalytics-staging

production:
  <<: *common
  database: xikolo-learnanalytics-production
