#  ElasticDatasource Database Configuration

common: &common
  datasource_adapter: 'ElasticDatasource'
  key: 'referral'
  name: 'Referrer'
  description: 'Tracking internal and external referrers...'

development:
  <<: *common
  host: 'localhost'
  port: '9200'
  index: 'lanalytics'
  user: 'lanalytics'
  password: 'lanalytics'

test:
  <<: *common

integration:
  <<: *common
  host: 'localhost'
  port: '9200'
  index: 'lanalytics'
  user: 'lanalytics'
  password: 'lanalytics'

staging:
  <<: *common
  host: 'localhost'
  port: '10200'
  index: 'lanalytics'
  user: 'lanalytics'
  password: 'lanalytics'

production:
  <<: *common
